# Generated by Django 4.2.5 on 2024-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_userorder_is_active_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purchase_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
