# Generated by Django 4.2.5 on 2024-06-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_purchase_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='coffee',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='flour',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugar',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='storage',
            name='name',
            field=models.CharField(choices=[('sugar', 'Sugar'), ('coffee', 'Coffee'), ('flour', 'Flour'), ('chocolate', 'Chocolate')], max_length=100),
        ),
    ]
