# Generated by Django 4.2.5 on 2024-06-27 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_orderproduct_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
