# Generated by Django 4.2.5 on 2024-06-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_alter_storage_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
