# Generated by Django 4.2.5 on 2024-06-28 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_storage_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
