# Generated by Django 4.2.5 on 2024-06-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_userorder_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default/product.png', upload_to='products/'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='default/user.jpg', upload_to='profiles/'),
        ),
    ]
